<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $medications = [
            [
                'name' => 'Paracetamol',
                'description' => 'Paracetamol is a common pain reliever and fever reducer.',
                'ingredient' => 'Paracetamol 500mg',
                'form' => 'Tablet',
                'usage' => 'For relief of mild to moderate pain and fever.',
                'strength' => '500mg',
                'manufacturer' => 'Acme Pharmaceuticals',
                'price' => 5.99,
            ],
            [
                'name' => 'Ibuprofen',
                'description' => 'Ibuprofen is an anti-inflammatory drug used for pain relief.',
                'ingredient' => 'Ibuprofen 200mg',
                'form' => 'Tablet',
                'usage' => 'For relief of pain and inflammation.',
                'strength' => '200mg',
                'manufacturer' => 'HealthCorp',
                'price' => 7.49,
            ],
            [
                'name' => 'Amoxicillin',
                'description' => 'Amoxicillin is an antibiotic used to treat bacterial infections.',
                'ingredient' => 'Amoxicillin 250mg',
                'form' => 'Capsule',
                'usage' => 'For treatment of bacterial infections.',
                'strength' => '250mg',
                'manufacturer' => 'PharmaGen',
                'price' => 12.99,
            ],
            [
                'name' => 'Cetirizine',
                'description' => 'Cetirizine is an antihistamine used to relieve allergy symptoms.',
                'ingredient' => 'Cetirizine 10mg',
                'form' => 'Tablet',
                'usage' => 'For relief of allergy symptoms such as runny nose and sneezing.',
                'strength' => '10mg',
                'manufacturer' => 'AllergyFree',
                'price' => 8.99,
            ],
            [
                'name' => 'Metformin',
                'description' => 'Metformin is a medication used to treat type 2 diabetes.',
                'ingredient' => 'Metformin 500mg',
                'form' => 'Tablet',
                'usage' => 'For management of type 2 diabetes.',
                'strength' => '500mg',
                'manufacturer' => 'DiabetesCare',
                'price' => 15.99,
            ],
            [
                'name' => 'Lisinopril',
                'description' => 'Lisinopril is used to treat high blood pressure and heart failure.',
                'ingredient' => 'Lisinopril 10mg',
                'form' => 'Tablet',
                'usage' => 'For treatment of high blood pressure and heart failure.',
                'strength' => '10mg',
                'manufacturer' => 'HeartMed',
                'price' => 9.99,
            ],
            [
                'name' => 'Amlodipine',
                'description' => 'Amlodipine is used to treat high blood pressure and chest pain.',
                'ingredient' => 'Amlodipine 5mg',
                'form' => 'Tablet',
                'usage' => 'For treatment of high blood pressure and chest pain.',
                'strength' => '5mg',
                'manufacturer' => 'CardioHealth',
                'price' => 14.99,
            ],
            [
                'name' => 'Omeprazole',
                'description' => 'Omeprazole is used to treat gastroesophageal reflux disease (GERD).',
                'ingredient' => 'Omeprazole 20mg',
                'form' => 'Capsule',
                'usage' => 'For treatment of gastroesophageal reflux disease.',
                'strength' => '20mg',
                'manufacturer' => 'StomachCare',
                'price' => 10.49,
            ],
            [
                'name' => 'Atorvastatin',
                'description' => 'Atorvastatin is used to lower cholesterol and reduce the risk of heart disease.',
                'ingredient' => 'Atorvastatin 10mg',
                'form' => 'Tablet',
                'usage' => 'For lowering cholesterol and reducing heart disease risk.',
                'strength' => '10mg',
                'manufacturer' => 'CholesterolBusters',
                'price' => 19.99,
            ],
            [
                'name' => 'Simvastatin',
                'description' => 'Simvastatin is used to lower cholesterol and triglycerides in the blood.',
                'ingredient' => 'Simvastatin 20mg',
                'form' => 'Tablet',
                'usage' => 'For lowering cholesterol and triglycerides.',
                'strength' => '20mg',
                'manufacturer' => 'LipidCare',
                'price' => 18.49,
            ],
            [
                'name' => 'Ciprofloxacin',
                'description' => 'Ciprofloxacin is an antibiotic used to treat bacterial infections.',
                'ingredient' => 'Ciprofloxacin 500mg',
                'form' => 'Tablet',
                'usage' => 'For treatment of bacterial infections.',
                'strength' => '500mg',
                'manufacturer' => 'AntibioticInc',
                'price' => 12.99,
            ],
            [
                'name' => 'Hydrochlorothiazide',
                'description' => 'Hydrochlorothiazide is used to treat high blood pressure and edema.',
                'ingredient' => 'Hydrochlorothiazide 25mg',
                'form' => 'Tablet',
                'usage' => 'For treatment of high blood pressure and edema.',
                'strength' => '25mg',
                'manufacturer' => 'BloodPressureCare',
                'price' => 9.49,
            ],
            [
                'name' => 'Furosemide',
                'description' => 'Furosemide is a diuretic used to treat fluid retention and swelling.',
                'ingredient' => 'Furosemide 40mg',
                'form' => 'Tablet',
                'usage' => 'For treatment of fluid retention and swelling.',
                'strength' => '40mg',
                'manufacturer' => 'DiureticSolutions',
                'price' => 8.99,
            ],
            [
                'name' => 'Levothyroxine',
                'description' => 'Levothyroxine is used to treat hypothyroidism.',
                'ingredient' => 'Levothyroxine 50mcg',
                'form' => 'Tablet',
                'usage' => 'For treatment of hypothyroidism.',
                'strength' => '50mcg',
                'manufacturer' => 'ThyroidCare',
                'price' => 10.99,
            ],
            [
                'name' => 'Azithromycin',
                'description' => 'Azithromycin is an antibiotic used to treat various infections.',
                'ingredient' => 'Azithromycin 250mg',
                'form' => 'Tablet',
                'usage' => 'For treatment of bacterial infections.',
                'strength' => '250mg',
                'manufacturer' => 'AntibioticInc',
                'price' => 11.49,
            ],
            [
                'name' => 'Clindamycin',
                'description' => 'Clindamycin is an antibiotic used to treat bacterial infections.',
                'ingredient' => 'Clindamycin 300mg',
                'form' => 'Capsule',
                'usage' => 'For treatment of bacterial infections.',
                'strength' => '300mg',
                'manufacturer' => 'PharmaGen',
                'price' => 13.99,
            ],
            [
                'name' => 'Doxycycline',
                'description' => 'Doxycycline is an antibiotic used to treat bacterial infections.',
                'ingredient' => 'Doxycycline 100mg',
                'form' => 'Capsule',
                'usage' => 'For treatment of bacterial infections.',
                'strength' => '100mg',
                'manufacturer' => 'AntibioticInc',
                'price' => 14.49,
            ],
            [
                'name' => 'Metronidazole',
                'description' => 'Metronidazole is an antibiotic used to treat various infections.',
                'ingredient' => 'Metronidazole 500mg',
                'form' => 'Tablet',
                'usage' => 'For treatment of bacterial and protozoal infections.',
                'strength' => '500mg',
                'manufacturer' => 'PharmaGen',
                'price' => 12.49,
            ],
            [
                'name' => 'Warfarin',
                'description' => 'Warfarin is an anticoagulant used to prevent blood clots.',
                'ingredient' => 'Warfarin 5mg',
                'form' => 'Tablet',
                'usage' => 'For prevention of blood clots.',
                'strength' => '5mg',
                'manufacturer' => 'BloodCare',
                'price' => 16.99,
            ],
            [
                'name' => 'Losartan',
                'description' => 'Losartan is used to treat high blood pressure.',
                'ingredient' => 'Losartan 50mg',
                'form' => 'Tablet',
                'usage' => 'For treatment of high blood pressure.',
                'strength' => '50mg',
                'manufacturer' => 'HeartMed',
                'price' => 13.99,
            ],
        ];

        for ($i = 0; $i < 20; $i++) {
            DB::table('medications')->insert([
                'name' => $medications[$i % count($medications)]['name'],
                'description' => $medications[$i % count($medications)]['description'],
                'ingredient' => $medications[$i % count($medications)]['ingredient'],
                'form' => $medications[$i % count($medications)]['form'],
                'usage' => $medications[$i % count($medications)]['usage'],
                'strength' => $medications[$i % count($medications)]['strength'],
                'manufacturer' => $medications[$i % count($medications)]['manufacturer'],
                'price' => $medications[$i % count($medications)]['price'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
